### ISSUE TITLE
math pi statement

### ISSUE THREAD

**Issue by arielf212** [Lartu/ldpl-std#2]
the `store pi in <var>` statement is kind of useless in my opinion.
why not just have a const called `math.pi` or `std.math.pi` that holds the value of pi?
what value is gained from turning this into a sentence? in my opinion this sets a very bad precedent that everything needs to have a sentence, which is absolutely not true.

**Comment by Lartu** [comment]
You are absolutely right. This should be changed into a constant.

**Comment by Lartu** [comment]
Fixed
